# Generated by Django 3.2.9 on 2021-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='courses', to='student.Student'),
        ),
    ]
